export default [
    {
        id: 1,
        name: 'Android',
        class: 'fa-android',
        backgroundColor: '#000000',
        textColor: '#ffffff',
    },
    {
        id: 2,
        name: 'Angular',
        class: 'fa-angular',
        backgroundColor: '#000000',
        textColor: '#ffffff',
    },
    {
        id: 3,
        name: 'Apple',
        class: 'fa-apple',
        backgroundColor: '#000000',
        textColor: '#ffffff',    
    },
    {
        id: 4,
        name: 'AWS',
        class: 'fa-aws',
        backgroundColor: '#000000',
        textColor: '#ffffff',
    },
    {
        id: 5,
        name: 'Bootstrap',
        class: 'fa-bootstrap',
        backgroundColor: '#7952b3',
        textColor: '#ffffff',
    },
    {
        id: 6,
        name: 'DigitalOcean',
        class: 'fa-digital-ocean',
        backgroundColor: '#006aff',
        textColor: '#ffffff',
    },
    {
        id: 7,
        name: 'HTML5',
        class: 'fa-html5',
        backgroundColor: '#e44d26',
        textColor: '#ffffff',
    },
    {
        id: 8,
        name: 'CSS3',
        class: 'fa-css3-alt',
        backgroundColor: '#1b73ba',
        textColor: '#ffffff',
    },
    {
        id: 9,
        name: 'JavaScript',
        class: 'fa-js',
        backgroundColor: '#e3c914',
        textColor: '#ffffff',
    },
    {
        id: 10,
        name: 'PHP',
        class: 'fa-php',
        backgroundColor: '#4F5B93',
        textColor: '#ffffff',
    },
    {
        id: 11,
        name: 'Node.js',
        class: 'fa-node',
        backgroundColor: '#649c5e',
        textColor: '#ffffff',
    },
    {
        id: 12,
        name: 'Vue.js',
        class: 'fa-vuejs',
        backgroundColor: '#35495e',
        textColor: '#4fc08d',
    },
    {
        id: 13,
        name: 'React',
        class: 'fa-react',
        backgroundColor: '#61dafb',
        textColor: '#20232',
    },
];