export default [
    {
        id: 1,
        name: 'HTML5',
        class: 'fa-html5',
        backgroundColor: '#e44d26',
        textColor: '#ffffff',
        selected: true,
    },
    {
        id: 2,
        name: 'CSS3',
        class: 'fa-css3-alt',
        backgroundColor: '#1b73ba',
        textColor: '#ffffff',
        selected: false,
    },
    {
        id: 3,
        name: 'JavaScript',
        class: 'fa-js',
        backgroundColor: '#e3c914',
        textColor: '#ffffff',
        selected: false,
    },
    {
        id: 4,
        name: 'PHP',
        class: 'fa-php',
        backgroundColor: '#4F5B93',
        textColor: '#ffffff',
        selected: false,
    },
    {
        id: 5,
        name: 'Node.js',
        class: 'fa-node',
        backgroundColor: '#649c5e',
        textColor: '#ffffff',
        selected: false,
    },
    {
        id: 6,
        name: 'Vue.js',
        class: 'fa-vuejs',
        backgroundColor: '#35495e',
        textColor: '#4fc08d',
        selected: false,
    },
    {
        id: 7,
        name: 'React',
        class: 'fa-react',
        backgroundColor: '#61dafb',
        textColor: '#20232',
        selected: false,
    },
];