export default [
    {
        id: 1,
        name: 'Android',
        class: 'fa-android',
        backgroundColor: '#3ddc84',
        textColor: '#ffffff',
    },
    {
        id: 2,
        name: 'Angular',
        class: 'fa-angular',
        backgroundColor: '#dd0330',
        textColor: '#ffffff',
    },
    {
        id: 3,
        name: 'Apple',
        class: 'fa-apple',
        backgroundColor: '#000000',
        textColor: '#ffffff',    
    },
    {
        id: 4,
        name: 'AWS',
        class: 'fa-aws',
        backgroundColor: '#fe9900',
        textColor: '#ffffff',
    },
    {
        id: 5,
        name: 'Bitbucket',
        class: 'fa-bitbucket',
        backgroundColor: '#2684ff',
        textColor: '#ffffff',
    },
    {
        id: 6,
        name: 'Bootstrap',
        class: 'fa-bootstrap',
        backgroundColor: '#7952b3',
        textColor: '#ffffff',
    },
    {
        id: 7,
        name: 'Centos',
        class: 'fa-centos',
        backgroundColor: '#932279',
        textColor: '#ffffff',
    },
    {
        id: 8,
        name: 'Chrome',
        class: 'fa-chrome',
        backgroundColor: '#de4932',
        textColor: '#ffffff',
    },
    {
        id: 9,
        name: 'CSS3',
        class: 'fa-css3-alt',
        backgroundColor: '#1b73ba',
        textColor: '#ffffff',
    },
    {
        id: 10,
        name: 'DigitalOcean',
        class: 'fa-digital-ocean',
        backgroundColor: '#006aff',
        textColor: '#ffffff',
    },
    {
        id: 11,
        name: 'Docker',
        class: 'fa-docker',
        backgroundColor: '#2496ed',
        textColor: '#ffffff',
    },
    {
        id: 12,
        name: 'Drupal',
        class: 'fa-drupal',
        backgroundColor: '#009cde',
        textColor: '#ffffff',
    },
    {
        id: 13,
        name: 'Edge',
        class: 'fa-edge',
        backgroundColor: '#2fc2db',
        textColor: '#ffffff',
    },
    {
        id: 14,
        name: 'Elementor',
        class: 'fa-elementor',
        backgroundColor: '#c2305f',
        textColor: '#ffffff',
    },
    {
        id: 15,
        name: 'Figma',
        class: 'fa-figma',
        backgroundColor: '#a160fb',
        textColor: '#ffffff',
    },
    {
        id: 16,
        name: 'Firefox',
        class: 'fa-firefox',
        backgroundColor: '#ff5c4d',
        textColor: '#ffffff',
    },
    {
        id: 17,
        name: 'Git',
        class: 'fa-git-alt',
        backgroundColor: '#f05033',
        textColor: '#ffffff',
    },
    {
        id: 18,
        name: 'HTML5',
        class: 'fa-html5',
        backgroundColor: '#e44d26',
        textColor: '#ffffff',
    },
    {
        id: 19,
        name: 'Java',
        class: 'fa-java',
        backgroundColor: '#f8981d',
        textColor: '#ffffff',
    },
    {
        id: 20,
        name: 'Joomla',
        class: 'fa-joomla',
        backgroundColor: '#7ac143',
        textColor: '#ffffff',
    },
    {
        id: 21,
        name: 'JavaScript',
        class: 'fa-js',
        backgroundColor: '#e3c914',
        textColor: '#ffffff',
    },
    {
        id: 22,
        name: 'Laravel',
        class: 'fa-laravel',
        backgroundColor: '#ff2d20',
        textColor: '#ffffff',
    },
    {
        id: 23,
        name: 'Less',
        class: 'fa-less',
        backgroundColor: '#1d365d',
        textColor: '#ffffff',
    },
    {
        id: 24,
        name: 'Linode',
        class: 'fa-linode',
        backgroundColor: '#00b259',
        textColor: '#ffffff',
    },
    {
        id: 25,
        name: 'Linux',
        class: 'fa-linux',
        backgroundColor: '#ffcd00',
        textColor: '#ffffff',
    },
    {
        id: 26,
        name: 'Magento',
        class: 'fa-magento',
        backgroundColor: '#f26322',
        textColor: '#ffffff',
    },
    {
        id: 27,
        name: 'MODX',
        class: 'fa-modx',
        backgroundColor: '#00decc',
        textColor: '#ffffff',
    },
    {
        id: 28,
        name: 'Node.js',
        class: 'fa-node',
        backgroundColor: '#649c5e',
        textColor: '#ffffff',
    },
    {
        id: 29,
        name: 'npm',
        class: 'fa-npm',
        backgroundColor: '#cb3837',
        textColor: '#ffffff',
    },
    {
        id: 30,
        name: 'PHP',
        class: 'fa-php',
        backgroundColor: '#4F5B93',
        textColor: '#ffffff',
    },
    {
        id: 31,
        name: 'Python',
        class: 'fa-python',
        backgroundColor: '#3776aa',
        textColor: '#ffffff',
    },
    {
        id: 32,
        name: 'React',
        class: 'fa-react',
        backgroundColor: '#61dafb',
        textColor: '#ffffff',
    },
    {
        id: 33,
        name: 'Rust',
        class: 'fa-rust',
        backgroundColor: '#000000',
        textColor: '#ffffff',
    },
    {
        id: 34,
        name: 'Sass',
        class: 'fa-sass',
        backgroundColor: '#cd6799',
        textColor: '#ffffff',
    },
    {
        id: 35,
        name: 'Shopify',
        class: 'fa-shopify',
        backgroundColor: '#95bf47',
        textColor: '#ffffff',
    },
    {
        id: 36,
        name: 'Sketch',
        class: 'fa-sketch',
        backgroundColor: '#ea6c00',
        textColor: '#ffffff',
    },
    {
        id: 37,
        name: 'Swift',
        class: 'fa-swift',
        backgroundColor: '#f05138',
        textColor: '#ffffff',
    },
    {
        id: 38,
        name: 'Ubuntu',
        class: 'fa-ubuntu',
        backgroundColor: '#dd4814',
        textColor: '#ffffff',
    },
    {
        id: 39,
        name: 'Vue.js',
        class: 'fa-vuejs',
        backgroundColor: '#4fc08d',
        textColor: '#ffffff',
    },
    {
        id: 40,
        name: 'Wordpress',
        class: 'fa-wordpress',
        backgroundColor: '#21759b',
        textColor: '#ffffff',
    },
    {
        id: 41,
        name: 'Yarn',
        class: 'fa-yarn',
        backgroundColor: '#368fb9',
        textColor: '#ffffff',
    },
];